### ISSUE TITLE
Loading uncompressed file results in blank screen and hang

### ISSUE THREAD

**Issue by xlar54** [mist64/80columns#10]
built an uncompressed version, and LOAD"...",8,1 

wanting to SYS 51200 but during the load it just blanks the screen and drive hangs.

**Comment by jepler** [comment]
Because the character set data is loaded "under" the I/O region at $d000, it is not possible to directly load the uncompressed version to its intended use address. The "exomizer" uncruncher handles this correctly when uncrunching. I've proposed an addition to the README to explain this, see #14.
